### ISSUE TITLE
Update seed file

### ISSUE THREAD

**Issue by rutaitp** [GoLive-Radio/GoLive#55]
- [ ] change logoUrl on stations
- [ ] add data to join table

**Comment by Mils-1** [comment]
Add this link for the image for 'Tech'd Out'

https://s3-us-west-2.amazonaws.com/anchor-generated-image-bank/production/podcast_uploaded_nologo/433449/433449-1524787291548-e60fdacc9a1c2.jpg

**Comment by Mils-1** [comment]
PR #71 merged
